name: Generic SLSA Generator

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      subjects: ${{ steps.hashes.outputs.digest }}
      
    steps:
    - run: echo "artifact" > artifact.txt
  
    - run: |
        sha256sum artifact.txt | base64 -w0 > digest.txt
        echo "digest=$(cat digest.txt)" >> $GITHUB_OUTPUT
      id: hashes
      
  provenance:
    needs:
      - build
    permissions:
      actions: read
      id-token: write
      contents: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.9.0
    with:
      base64-subjects: "${{ needs.build.outputs.subjects }}"
