name: Generic SLSA Generator

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      subjects-as-file: ${{ steps.hashes.outputs.handle }}
      
    steps:
    - run: echo "artifact" > artifact.txt
  
    - uses: slsa-framework/slsa-github-generator/actions/generator/generic/create-base64-subjects-from-file@v1.9.0
      id: hashes
      with:
        path: large_digests_file.text
      
  provenance:
    needs:
      - build
    permissions:
      actions: read # Needed for detection of GitHub Actions environment.
      id-token: write # Needed for provenance signing and ID
      contents: write # Needed for release uploads
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.9.0
    with:
      base64-subjects-as-file: "${{ needs.build.outputs.subjects-as-file }}"
